services:
  db:
    image: postgres:15-alpine
    container_name: notesmg_container
    restart: always
    environment:
      POSTGRES_DB: notesmg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - notes_network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=123
      - DATABASE_URL=postgresql://postgres:123@localhost:5432/notesmg
    depends_on:
      - db
    networks:
      - notes_network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8080/api}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - notes_network

volumes:
  db_data:


networks:
  notes_network:
    driver: bridge
